version: "3"

services:
  mysql:
    image: mysql:8.0
    volumes:
      - ../volumes/dbdata:/var/lib/mysql
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=flarum
      - MYSQL_USER=flarum
      - MYSQL_PASSWORD=flarum
    restart: unless-stopped

  flarum:
    image: shinsenter/flarum:latest
    container_name: flarum
    volumes:
      - ../volumes/html:/var/www/html
      - ../packages:/var/www/html/packages
      - ./root/etc/cron.d/flarum:/etc/cron.d/flarum
      - ./root/startup/add-flarum:/startup/add-flarum
    networks:
      - flarum-frontend
      - backend
    ports:
      - "8000:80"
    depends_on:
      - mysql
    restart: unless-stopped

  nginx:
    image: mesudip/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/ssl:/etc/ssl
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - flarum-frontend
    restart: unless-stopped

networks:
  flarum-frontend:
    external: true
  backend:
